# This is an empty template playbook
# You can write your custom configuration here

- name: disable qxl
  hosts:
    - routers
    - hosts
  gather_facts: yes
  become: yes
  become_user: root

  tasks:
    - name: disable qxl
      include_role:
        name: disable-qxl
      when: ansible_os_family == 'Debian'


- name: user access
  hosts:
    - user_accessible_nodes
  gather_facts: no
  become: yes
  become_user: root
  roles:
    - role: kypo-user-access
      kypo_user_access_password: 'kypo'

- name: Update apt and install maven
  hosts:
    - smart-meter
    - concentrator
  gather_facts: no
  become: yes
  become_user: root
  tasks:
  - name: Update apt packages
    become: yes
    apt:
      update_cache: yes
      cache_valid_time: 86400 

  - name: Install maven
    become: yes
    apt:
      pkg:
       - maven

- name: Smart-meter setup
  hosts:
    - smart-meter
  gather_facts: no
  become: yes
  become_user: root
  tasks: 
  - name: Clone gurux repository
    become: yes
    git:
       repo: https://github.com/DanyMo20/gurux.git
       dest: /home/ubuntu/repo
       clone: yes
  
  - name: cd folder and mvn clean package	
    command: mvn clean package
    become: yes
    become_user: root
    args:
      chdir: /home/ubuntu/repo/gurux/gurux.dlms.server.example.java/

- name: Concentrator setup
  hosts:
    - concentrator
  gather_facts: no
  become: yes
  become_user: root
  tasks: 
  - name: Clone gurux repository
    become: yes
    git:
       repo: https://github.com/DanyMo20/gurux.git
       dest: /home/ubuntu/repo
       clone: yes
     
  - name: cd folder and mvn clean package	
    command: mvn clean package
    become: yes
    become_user: root
    args:
      chdir: /home/ubuntu/repo/gurux/gurux.dlms.server.example.java/
